College=input("College Name : ")
Name=input("Name : ")
Course=input("Course : ")
Batch=input("Batch : ")
Roll_No=input("Roll Number : ")
ID_NO=Batch+"-"+Course+"-"+Roll_No
print("="*30)
print("     COLLEGE ID CARD       ")
print("="*30)
#print("******BIBS******")
print("College : ",College)
print("Name    : ",Name)
print("Course  : ",Course)
print("Batch   : ",Batch)
print("Roll No : ",Roll_No)
print("ID NO   : ",ID_NO)
print("="*30)
