#student grade
Grade=('C','D','A','A','B','B','B','A','A')
print(type(Grade))
A_grade=Grade.count('A')
print(A_grade)
B_grade=Grade.count('B')
print(B_grade)
C_grade=Grade.count('C')
print(C_grade)
D_grade=Grade.count('D')
print(D_grade)
# Tuple method
channel=("dd","star","sony","zee","dd","sab")
print("Channel count(dd) = ",channel.count("dd"))
print("Channel Index(dd) = ",channel.index("dd"))
print("Channel count(zee) = ",channel.count("zee"))
print("Channel Index(zee) = ",channel.index("zee"))
print("Channel count(sab) = ",channel.count("sab"))
print("Channel Index(sab) = ",channel.index("sab"))
